<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Swashbuckle.AspNetCore" Version="6.6.2" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Entrevisto.Application\Entrevisto.Application.csproj" />
    <ProjectReference Include="..\Entrevisto.Domain\Entrevisto.Domain.csproj" />
    <ProjectReference Include="..\Entrevisto.Infrastructure\Entrevisto.Infrastructure.csproj" />
  </ItemGroup>

</Project>
